# Generated by Django 5.1.5 on 2025-01-28 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_tagihan', models.CharField(max_length=20, unique=True, verbose_name='Nomor Tagihan')),
                ('tanggal_terbit', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Terbit')),
                ('bulan', models.CharField(choices=[('01', 'Januari'), ('02', 'Februari'), ('03', 'Maret'), ('04', 'April'), ('05', 'Mei'), ('06', 'Juni'), ('07', 'Juli'), ('08', 'Agustus'), ('09', 'September'), ('10', 'Oktober'), ('11', 'November'), ('12', 'Desember')], max_length=2, verbose_name='Bulan')),
                ('periode', models.CharField(max_length=20, verbose_name='Periode')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah')),
                ('status', models.CharField(choices=[('belum_lunas', 'Belum Lunas'), ('lunas', 'Lunas')], default='belum_lunas', max_length=20, verbose_name='Status')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan', to='pengguna.pelanggan', verbose_name='Pelanggan')),
            ],
            options={
                'verbose_name': 'Tagihan',
                'verbose_name_plural': 'Tagihan',
                'ordering': ['-tanggal_terbit'],
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembayaran', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Pembayaran')),
                ('jumlah_dibayar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah Dibayar')),
                ('metode_pembayaran', models.CharField(choices=[('transfer', 'Transfer Bank'), ('tunai', 'Tunai'), ('dompet_digital', 'Dompet Digital')], max_length=30, verbose_name='Metode Pembayaran')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('tagihan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='transaksi.tagihan', verbose_name='Tagihan')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
                'ordering': ['-tanggal_pembayaran'],
            },
        ),
    ]
